### ISSUE TITLE
Items with Active Token Lighting effects cause token size to return to the prototype token's default size.

### ISSUE THREAD

**Issue by confucianscholar** [kandashi/Active-Token-Lighting#10]
**Experienced behaviour:**
A token which has been changed in size compared to its prototype will be reset to the prototype's size upon certain interactions with an item in their inventory with an Active Token Lighting effect. This includes equipping/unequipping the item, or attempting to edit the effect. In the video below, you can see the re-sizing occurs when interacting with a torch (imported from the Token Lighting premade compendium and only modified to enable the "Enabled when equipped" setting in the item's DAE configuration). The resizing does not occur when interacting with other items with dynamic active effects, such as the Berserker Axe in the video below (boosts HP based on level when equipped).

https://user-images.githubusercontent.com/77675012/105565456-327e8100-5d6a-11eb-97d2-692db9421356.mp4

**Steps to reproduce:**
1. Activate DAE and ATL modules.
2. Import the torch from the premade compendium provided by ATL, or configure your own item with an ATL effect.
3. (Optional) Ensure the item's DAE configuration has "Enable when equipped" active
4. Configure a prototype token to have size X,Y (width,height).
5. Add the torch to the token's inventory.
6. Add the token to the play area and change its size P,Q (P != X, Q != Y).
7. In the active token's character sheet do one of the following:
    1) equip the torch (if #3 above was configured),
    2) active the torch effect from the token's effects tab, or
    3) view/edit the torch and then close the torch item window (with or without making any changes).
8. Observe the token revert to its prototype token's default size.

**Expected behaviour:**
The active token should maintain any size changes made to it regardless of any changes made to (or interactions with items using) active effects related to ATL.

**Test Environment:**
- Foundry 0.7.9 + DnD5e 1.2.4
- Dynamic effects using Active Effects 0.2.37
- Active Token Lighting 0.1.1
- No other modules were active* 
*(Forien's Copy Environment 1.1.1 is active in the attached video for conveniently re-enabling all modules after recording, but the issue occurs with it disabled as well.)

**Comment by kandashi** [comment]
Noted, this was skipped over in the original release, I'll add a setting to turn on size checking, which should help aleviate this
