### ISSUE TITLE
Some tokens change sizes when loading into a map for the first time.

### ISSUE THREAD

**Issue by GambetTV** [kandashi/Active-Token-Lighting#100]
This is an issue with the most recent update to this mod. Any token with an effect placed on it with an ATL attribute will override the scale setting of the token, even if the scale it not noted in the module. It seems to revert the token to its default size in this instance.

For instance, a token with the Active Effect: ATL.dimLight, which as far as I know should have nothing to do with the scaling of the token, will revert the token when making the effect active/inactive, or even when loading into a map with that token on it. There are numerous reasons why I might want to temporarily change a token's scale, and this module now hinders the ability to do that. It also makes it conflict with a variety of other modules out there now.

Hopefully you can disable whatever is causing this to happen. Thanks!

**Comment by kandashi** [comment]
This is (oddly) intentional. ATE now uses the prototype token as a default baseline to compare against. This means that it will apply those settings + any ATE effects. Im sorry if that change is undesirable for you, but there isnt any real way to avoid this issue that I can think of. 
You are welcome to roll back to the previous version of ATE if that worked better for your use-case

**Comment by GambetTV** [comment]
So I definitely understand the rationale for this, but there seems to be a variety of what I assume are unintentional side-effects caused by this change. I think the biggest way I can define it is as a lack of consistency/control for a DM over a scene if they are using this module. This goes beyond incompatibilities with other mods. For instance, something as simple as token rotation, will now automatically get reset to the default values every time you load into a scene. So if I've set a group of characters up to be, say, sitting in chairs facing in various directions with respect to where the chairs are pointing, upon loading into the map, all those tokens, if they have any ATE effects present, will now drop to their default rotation. 

If I want to change a token's disposition temporarily, just for the map they're on, perhaps to hide the fact that they're an enemy, that will automatically be reset as well. Tint Color, Z-Index, Token Opacity, Vision Settings, Lighting Settings, even Display Bar settings all get automatically reset, and none of this has anything to do with incompatibility with other modules, it just makes the DM's control over tokens and scenes severely handicapped.

If there's no way to avoid this issue then fair enough, but I think this introduces a lot of clunkiness that would be undesirable for a lot of people, and maybe deserves a second look at. Until then, I'm happy to use the previous version for as long as it's compatible with the most recent versions of Foundry. I appreciate what you've done either way!

**Comment by tjlanza** [comment]
I too believe this is change in behavior, forcibly changing everything back to the token prototype, was a bad idea. I have tokens that use limited cone lights sources (toggled via ATE) that automatically reset position.

It should change **only** aspects specified in the ATE-bearing effect, and not do **anything** else. Not to be too pointed, but it is no longer "Active Token Effects" it is "Smash The Token Back In The Box And Only Do What This Module Says".

**Comment by Buuuurce** [comment]
I'm having a similar problem where a new preset or a copy of a base preset would also change a large token back to base size when the effect was turned on. A workaround was to make another copy of the preset with the large size though it's a bother to update multiple presets if I want to change something.
