### ISSUE TITLE
BUG: TypeError: Cannot read properties of null (reading 'effects')

### ISSUE THREAD

**Issue by Jonwh25** [kandashi/Active-Token-Lighting#102]
**Describe the bug**
I'm not seeing anything negative in the actual use of the module. Things seem to work.  However I'm seeing an error in the console when I'm first logging into the game. The error is as follows:

![image](https://user-images.githubusercontent.com/60674327/164077197-c5d6f23f-b4b8-44b1-8366-3e6f27cf3302.png)

**Comment by Doresain** [comment]
Same. Pretty sure it started since the last update.

**Comment by Brimcon** [comment]
Seeing this error  as well, and the issue I'm finding is the fact that Lighting effects do not turn off when the Active Effect is removed.

**Comment by p4535992** [comment]
made this pr about it https://github.com/kandashi/Active-Token-Lighting/pull/105

**Comment by davelacorneille** [comment]
Any update about it?  I still have this error frequently.

**Comment by kaelad02** [comment]
Was fixed in v0.5.0
