### ISSUE TITLE
Adding new preset uses _id as name

### ISSUE THREAD

**Issue by hirnstrudel** [kandashi/Active-Token-Lighting#103]
**Describe the bug**
Adding new ATL presets are saved with their random ID as name.
This also effects the update of built-in presets.

**To Reproduce**
1. Open "ATL Presets" Dialog
2. Click "Add New"
3. Enter "testing" as Preset Name and click "Add Preset"
4. Open "ATL Presets" Dialog
5. There is a new preset called "<random_id>"

**Expected behavior**
There should be a new preset called "testing"

**Environment:**
 - Foundry Version 9.269
 - Module Version 0.4.01
 - All Modules Disabled: Yes

**Additional context**
It seems to me that https://github.com/kandashi/Active-Token-Lighting/blob/d6e9d0fc4a69850147ab381b294f6ed5f0fd607d/src/activeLighting.js#L408 should actually be:
`let name = html.find("#name")[0].value`

**Comment by hirnstrudel** [comment]
Indeed `let name = html.find("#name")[0].value` works as expected.

**Comment by kaelad02** [comment]
This was fixed in v0.5.0
