### ISSUE TITLE
Torches place template, produce no light

### ISSUE THREAD

**Issue by Orionox** [kandashi/Active-Token-Lighting#104]
**Describe the bug**
When using a torch, you are prompted to place a template and consume resources. After accepting, you place a template, but no light is emitted from the template or your character. 

**To Reproduce**
1. Place torch in inventory, from ATL compendium
2. Use a torch
3. Place the template
4. No light is emitted from the template or player.
5. 
**Expected behavior**
After using a torch I would expect the light to be emitted from something. Either them template I'm prompted to place or my character that is using the torch

**Comment by Jeznar** [comment]
After more fiddling, the specific cause of the compendium issue reported here is that the items are provided with the effects suspended.  That's not _wrong_ just not what I would have expected.

After placing one of these items from the compendium, the Suspended box on the effect needs to be clicked off and submitted as shown in my annotated screen snap.

<img width="1032" alt="Screen Shot 2022-05-05 at 10 15 16 AM" src="https://user-images.githubusercontent.com/95548360/166944175-1ddf0dca-7809-4402-9371-c9396b60386e.png">
