### ISSUE TITLE
Expand ATL for advanced settings

### ISSUE THREAD

**Issue by Aggrus** [kandashi/Active-Token-Lighting#110]
If possible, it would be nice to have ATL be able to configure stuff like light shadows, coloration tecniques, sight limit, etc.

**Comment by kaelad02** [comment]
I recognize sight limit as an option that Perfect Vision adds but I don't recognize the other two. I assume those are part of some modules as well?

Sight Limit is set on the token as a flag so ATE is able to change it. I've actually added it to the wiki page linked below. If you can tell me what the other two are from, I can see how they're handled and if/how ATE can change them.

https://github.com/kandashi/Active-Token-Lighting/wiki/Key-Reference#module-specific-settings
