### ISSUE TITLE
Update depreciated fields for V10

### ISSUE THREAD

**Issue by Arnold-Muralt** [kandashi/Active-Token-Lighting#111]
When Installing on V10.283, Errors occur on installation, 
Metadata Validation failed for module ATL, file "/styles/ATL.css" included by ATL does not exist

ATL contains the depreciated "entity" field which must be migrated to "type"
ATL uses "author" which is being depreciated in favor of "authors"
ATL is using the old flat core compatibility fields, which are being depreciated in favor of "compatibility" object

**Comment by bearsy1** [comment]
+1
This module has become essential for my games and I would really like to be able to use it with the added benefits of v10 foundry.

**Comment by kandashi** [comment]
None of my modules are yet updated for v10. Do not expect quick updates as I have very little time on my hands right now

**Comment by LanMan04** [comment]
+1 same issue here

**Comment by Morters** [comment]
I believe we have a PR ready for V10. Is it possible to merge it with main? Is there any other thing that we need to wait on?

**Comment by CaosFR** [comment]
@kandashi Hi, any news, tests, or a timeline for the update ?

**Comment by linxcat** [comment]
If we are yo go by the same "waiting on PR acceptance" problem also experienced in this other @kandashi module, a fork may be appropriate for the time being or permanently: https://github.com/kandashi/midi-srd/issues/25#issuecomment-1309719026

**Comment by kaelad02** [comment]
fixed in #113 and v0.5.0 supports Foundry v10
