### ISSUE TITLE
[v10] installations fails, missing styles folder

### ISSUE THREAD

**Issue by vt-tom** [kandashi/Active-Token-Lighting#114]
**Describe the bug**
The reinstallation under v10 fails because the styles folder and the files in it are missing.

**To Reproduce**
1. open a v10 installation
2. go to modules
3. open the console
4. install ATL

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/188560322-5a0090ab-fd6c-4c39-a4eb-a31ce80a397a.png)

**Environment:**
 - Hosting - Molten Hosting (also tested it local)
 - Browser [e.g. chrome, safari] Chrome
 - Foundry Version [e.g. 0.8.8] 10.284 
 - Module Version [e.g 0.1.42]  0.4.01

**Comment by afolivieri** [comment]
Same Issues here, it doesn't even "Install" and the error persists even after deleting manually the folder in modules.
I'm on a Ubuntu machine, NGINX reverse proxi, Foundry 10.285, ATL 0.4.01

**Comment by kenkrista** [comment]
**Workaround to install the module** 

For the less tech-savvy people (like myself)...

After the install fails, you'll find a partial installation consisting of the following directories and files in foundrydata/Data/modules/:
- ATL/README.md
- ATL/module.json
- ATL/packs/
- ATL/packs/premade
- ATL/src/
- ATL/src/activeLighting.js
- ATL/src/updateManager.js

If you manually create the ATL/styles/ directory; ATL/styles/ATL.css file; and copy and paste the CSS file contents from the repository into the local ATL.css file you created, the module will appear as installed and you can lock it to prevent updates. I can't speak to whether or not there are any issues with the module itself once its running in v10, but it seems to work fine for me so far.

**Comment by BathToast** [comment]
> If you manually create the ATL/styles/ directory; ATL/styles/ATL.css file; and copy and paste the CSS file contents from the repository into the local ATL.css file you created, the module will appear as installed and you can lock it to prevent updates. I can't speak to whether or not there are any issues with the module itself once its running in v10, but it seems to work fine for me so far.

When i attempt this it still throws the error and just deletes the file and the directory. Any thoughts?

**Comment by NateThompson114** [comment]
> > If you manually create the ATL/styles/ directory; ATL/styles/ATL.css file; and copy and paste the CSS file contents from the repository into the local ATL.css file you created, the module will appear as installed and you can lock it to prevent updates. I can't speak to whether or not there are any issues with the module itself once its running in v10, but it seems to work fine for me so far.
> 
> When i attempt this it still throws the error and just deletes the file and the directory. Any thoughts?

It's not a fix to install...

1. Install the module (This will seem to fail, but in your folder for modules, you should see a folder called ATL [...AppData\Local\FoundryVTT\Data\modules]) 
2. Create a folder called **styles**
3. Download this CSS file _https://raw.githubusercontent.com/kandashi/Active-Token-Lighting/main/styles/ATL.css_ into your **styles** folder that you just created
4. **_Restart Foundry_**
5. Go to your **Add-on Modules**
6. Click the **Lock** icon on the right side of Active Token Effects (this will stop you from accidentally blowing away what you just did)
7. Check back here often until a v10 release is done,
8. Once(if) a v10 update is completed unlock and update

**Comment by CaosFR** [comment]
@NateThompson114 Thanks for the tips until @kandashi update (happy dev).

**Comment by Gacky2k** [comment]
@NateThompson114  THANK YOU SIR!  This worked perfectly!

**Comment by zabu61** [comment]
@NateThompson114 Confirmed that this also works to eliminate the error in 10 build 288
Thanks so much!

**Comment by sharkbruhaha** [comment]
thanks a ton @NateThompson114 !

**Comment by kaelad02** [comment]
fixed in #113 and available in v0.5.0
