### ISSUE TITLE
Quick Reference Guide (v10)

### ISSUE THREAD

**Issue by MaxPat931** [kandashi/Active-Token-Lighting#115]
I wrote up this [Quick Reference Guide](https://hackmd.io/LL_Sx0D8RYeL-1ddqw726g) for the usable ATL attribute keys in v10 and what values they accept, I think it would be useful to add as a resource here when the v10 release is ready.

Raw .md available here: https://raw.githubusercontent.com/MaxPat931/Macros/main/QuickReference.md

**Comment by sharkbruhaha** [comment]
yes please! Thank you for the write-up @MaxPat931 !!

**Comment by brunocalado** [comment]
Add this documentation and some snippets of how to create new presets.

**Comment by kaelad02** [comment]
@MaxPat931 I'm not going to include the testing notes at the end. I assume that's okay, right?

**Comment by kaelad02** [comment]
I created a wiki page for this, linked below. I added a little intro text, added the `preset` key, and skipped the testing notes section. I'll keep this issue open for a few more days (maybe until the weekend) to get immediate feedback.

https://github.com/kandashi/Active-Token-Lighting/wiki/Key-Reference

**Comment by brunocalado** [comment]
Can you add working snippets of how to use? Noob friendly

please

ATL.AddPreset() takes 2 arguments, the name of the preset to add and the object to add
ATL.RemovePreset() takes the name of the preset to be removed
ATL.GeneratePreset() will open a dialog to create a new preset
ATL.UpdatePresets() will open a dialog to edit,delete,add presets

**Comment by MaxPat931** [comment]
Looks good, I think leaving out the testing notes is fine.
Might want to either remove `ATL.texture.offsetX/Y`  or note that they dont do anything (core thing, not related to the module)
And maybe a note for `ATL.light.darkness.min/max` since it's not something that is accessible in the UI but is a neat feature

**Comment by MaxPat931** [comment]
I updated my file in the original link to separate everything out into sections and using tables (inspired after looking at AdvRem's docs!) but I didnt really do anything with the Description column (I think most are self explanatory so it might not really be necessary, but there are a couple that it could be helpful), but if you like that format better, it's there

**Comment by kaelad02** [comment]
Done
