### ISSUE TITLE
Cannot adjust the Sight Limit property

### ISSUE THREAD

**Issue by Masterfuzzfuzz** [kandashi/Active-Token-Lighting#117]
**Describe the bug**
Unable to add an active effect that affects the Sight Limit property of a token. I've tried ATL.SightLimit, ATL.Sight.Limit, and any other combination I can think of. Is this not supported?

**Expected behavior**
To be able to select SightLimit as a dropdown and set a value like the other site properties.

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Foundry Version: v9 Build 280
 - Module Version: 0.4.01
 - All Modules Disabled: No
 - Module List if no:  Dynamic Active Effects

**Comment by Division4Studios** [comment]
I can confirm this is an issue.  Ivestigated this as well with Mr.Primate

**Comment by kaelad02** [comment]
Is Sight Limit something that the Perfect Vision module adds?

**Comment by kaelad02** [comment]
I installed Perfect Vision and figured out where the sight limit is stored. Not surprisingly, in a flag on the token. An active effect with this kind of change will work:

```
ATL.flags.perfect-vision.sight.range | Override | 30
```

**Comment by kaelad02** [comment]
I added it to the documentation on https://github.com/kandashi/Active-Token-Lighting/wiki/Key-Reference
