### ISSUE TITLE
ATL presets change token size, ATL dimensions set to width: blank, height: blank

### ISSUE THREAD

**Issue by TogaParty** [kandashi/Active-Token-Lighting#125]
**Describe the bug**
ATL presets change token size when applied.  When affected by an ATL preset, the token is forced to a given size if it isn't already (in my case medium, 5x5). 

**To Reproduce**
1. Setup an ATL preset.  Leave Dimensions blank.
2. Apply preset to a Gargantuan NPC

**Expected behavior**
Token size should not change with a lighting effect.

**Screenshots**

**Environment:**
 - OS: Win10
 - Browser Multiple
 - Foundry Version 10.291
 - Module Version Latest as of today, 2/5/23
 - All Modules Disabled: No
 - Module List if no: Multiple

**Additional context**

**Comment by TogaParty** [comment]
Also note that ratio is set to 1.

**Comment by kaelad02** [comment]
I noticed this too when working on some other issues. The presets that the module creates for you (e.g. torch) only contain settings to change the light properties so it won't touch things like height, width or scale. If, however, you create a new preset from scratch or a copy, then it'll be saved with all the settings and not just the ones you changed.

I would like to change the preset editor to make it so if you don't set something like scale then it won't be saved as part of the preset. I'm hoping it's possible to do without having to add checkboxes next to everything to indicate you want to change it.
