### ISSUE TITLE
Light is only visible to the owning token

### ISSUE THREAD

**Issue by renzo38** [kandashi/Active-Token-Lighting#138]
**Describe the bug**
I created a sword to reflect a **Flame Tongue**. When I activate it, the light is only visible to the token owning the sword.

**To Reproduce**
See images below

**Expected behavior**
Light for everyone (unless blind ;-) )

**Screenshots**
![image](https://github.com/kandashi/Active-Token-Lighting/assets/10115207/69e21431-a870-44f8-b041-7e092f97f732)

The animated gif can be found here (my post)

https://discord.com/channels/170995199584108546/513918036919713802/1117854166371532880

**Environment:**
 - OS: hosted on Linux Debian 12
 - Browser: Brave (latest)
 - Foundry Version 11
 - Module Version 0.6.2
 - All Modules Disabled: No
 - Module List if no:

**Comment by kaelad02** [comment]
What game system and version are you using?

**Comment by renzo38** [comment]
Hi, indeed I did not mention the system, it is dd5 **v2.2.1** with foundry **v11.301** and ATE module **v0.6.2**

**Comment by renzo38** [comment]
Huuuummm, seems that if I only activate your module, it works... I will try to find the module(s) which cause that and i will let you know, sorry for the inconvenience.

**Comment by renzo38** [comment]
After some tests, It seems to be a conflict/issue with **Levels** and/or **WallHeight** module(s)
