### ISSUE TITLE
ATL presets not affecting 5e NPCs

### ISSUE THREAD

**Issue by DishonoredRaven** [kandashi/Active-Token-Lighting#141]
Not entirely sure if this is a bug or just not a supported feature yet, but I'm putting it here. Pretty much exactly as title describes. ATL presets work for PCs but not NPCs.

https://github.com/kandashi/Active-Token-Lighting/assets/33526316/31234384-56be-4fc8-b2fd-b5092ba3cc69

**Comment by kaelad02** [comment]
Can I assume you found the problem and it wasn't ATE?
