### ISSUE TITLE
Ability to temporarily change token image like you can with width and height

### ISSUE THREAD

**Issue by SirAron111** [kandashi/Active-Token-Lighting#143]
**Is your feature request related to a problem? Please describe.**
I have a player who is a lycantrope and one who is a rune knight. I use the active effects ATL.width and ATL.height to automatically change the rune knight to a bigger size when the effect is active. And i would love to be able to do the same for the lycantrope whenever they shift to a hybrid form. is there a way to add a ATL.tokenimage or the like? That would, just for the time the effect is active, change the image of the token to a selected one? And back after the effect is removed or runs out?

**Describe the solution you'd like**
a way to have active effects temporarily change a tokens image to a well temporary one and back after the effect is removed.

**Describe alternatives you've considered**
Considered using a macro, but my macro bar is already clutter with a lot of stuff for traps and area scenery stuff. And i believe such a function would be nice.

**Comment by kaelad02** [comment]
You can do this with the `ATL.texture.src` key and set the value to the other token image. I would manually change the token image (don't save it though) just so you can copy the file path to make sure it works. Then you can include it in the active effect. For example:

```
ATL.texture.src | Overwrite | worlds/my-world/tokens/lycanthrope.png
```

And for future reference, I put the keys you can use in a wiki page: https://github.com/kandashi/Active-Token-Lighting/wiki/Key-Reference

**Comment by SirAron111** [comment]
cant seem to find it when i make an effect. it doesnt show up in the add effect tab. but most other keys do like width for example. It doesnt seem to register ATL.texture at all.
![Unbenannt](https://github.com/kandashi/Active-Token-Lighting/assets/39855956/648e5135-f321-4eef-aa71-40c35a5af3ed)
![Unbenannt2](https://github.com/kandashi/Active-Token-Lighting/assets/39855956/33432ff3-a62d-4f72-9962-00ef11bcf880)

**Comment by kaelad02** [comment]
DAE adds the drop-down in the Attribute Key column to make it easier to find. It won't have a complete list. I made a pass about a year ago to get some tweaked but I don't think we added them all. Just because it's not there doesn't mean it doesn't exist. Try it anyways.

**Comment by SirAron111** [comment]
Ahhh that really worked ok got it. i always thought the dropdown shows all keys and stuff and if nothing shows it doesn't exist. But this makes so many things so much better now, thx.
