### ISSUE TITLE
ATL preset changing unmodified values

### ISSUE THREAD

**Issue by lucaspicerni** [kandashi/Active-Token-Lighting#144]
Hello! I'm having [this problem](https://github.com/kandashi/Active-Token-Lighting/issues/125) with the "scale" and "vision mode" values. When creating a custom preset, even if you do not change these values, the preset is saved with the default values (basic vision mode and scale 1), therefore, whenever you use the preset, the token will have these settings changed undesirably.

I changed the world settings and edited the preset's scale and vision mode values to "null" as a test and it worked.

**To reproduce**:
1. Create a preset
2. Do not change the "scale" and "vision mode" values
3. Save
4. Use the preset on a token with a scale other than 1
5. Watch the token scale change

**Environment:**
 - Browser: Chrome
 - Foundry version: 10.303
 - Module version: 0.6.2

**Comment by kaelad02** [comment]
I'm not able to reproduce the issue. With the same Foundry and module version, I created a new preset named Large and set the height/width to 2. When I look at the preset in the settings, it's exactly what I expected:

```json
{
    "name": "Large",
    "width": 2,
    "height": 2,
    "id": "9ATp3A61CZLBU6kG"
}
```

Can you elaborate on what you're defining in your preset? Maybe changing a particular field is saving scale/visionMode when it shouldn't.

In fact, I'm seeing a different issue. I tried changing the scale value by dragging the slider and it won't save it at all. I check the preset after and `scale` isn't being saved.

**Comment by lucaspicerni** [comment]
I'll reproduce the bug again and annotate the walkthrough more elaborately over the next week, and report back then!

**Comment by kaelad02** [comment]
Fixed the issue with `scale` not being saved in the preset in version 0.7.0. If you find other preset issues, feel free to reopen this
