### ISSUE TITLE
effects not being applied/applied when equipping/unequipping in wfrp

### ISSUE THREAD

**Issue by StevenEvans1966** [kandashi/Active-Token-Lighting#149]
**To Reproduce**
add a wearable item with ATL.preset CUSTOM lantern effect.  equip/unequip

**Expected behavior**
equipping the item should change the token lighting to the lantern preset.  unequipping should remove lantern settings

**Comment by kaelad02** [comment]
Compatibility with WFRP4e was added to this module in version 0.7.0. Can you list the version of Foundry, WFRP4e, and ATE you are using? I just want to rule that out first.

**Comment by StevenEvans1966** [comment]
Foundary 11.315
WFRP4e: 7.03
ATE: 0.7.0

Sent from Mail for Windows

**Comment by StevenEvans1966** [comment]
I tried this with three “worn” item types weapon, armour and tapping [Clothing and Accessories] it only works with armour.  I would suggest a lantern should be a weapon as it is held in the hand. 

Sent from Mail for Windows

**Comment by kaelad02** [comment]
I don't know the WFRP4e system all that well, but we're out of ATE territory now. Now we're into how active effects work in that system, no longer an ATE issue.
Creating a miscellaneous item on the character sheet used the Trapping item type. I suppose you could use that, but it doesn't have a Worn toggle like armor does. Instead, you'd need to go to the Effects tab on the character sheet and toggle it that way.
