### ISSUE TITLE
[Feature Request] Change token scale

### ISSUE THREAD

**Issue by GhostwheelX** [kandashi/Active-Token-Lighting#153]
Might it be possible to add a flag that changes the scale of a token when added?

**Comment by kaelad02** [comment]
The token's data model is a bit odd. While the UI only shows one scale slider, under the hood there are two properties that control this. Have you tried setting `ATL.texture.scaleX` and `ATL.texture.scaleY`? Or did I misunderstand your request?

**Comment by GhostwheelX** [comment]
I'm still waiting another week or two before I update to v3 of D&D5e, so if those were added after v0.4.03 then I don't see them.

That said, it sounds like that's exactly what I'm looking for, so if those are present in the current version then that sounds like exactly what I'm looking for. Thank you very much!
