### ISSUE TITLE
Size documentation is wrong

### ISSUE THREAD

**Issue by JPMeehan** [kandashi/Active-Token-Lighting#22]
Code calls for the size flag to have two values on line 177

let { size, scale } = SizeFlag !== undefined ? SizeFlag : 0;

Readme documentation though calls for "Height, Width, Scale"

**Comment by kandashi** [comment]
This is a fix coming through soon, thanks for the catch

**Comment by BadIdeasBureau** [comment]
Any update on this, or suggestion as to what the proper keys/arguments for the size flags should be?

**Comment by kandashi** [comment]
Sorry, the keys are meant to be `height`, `width`, `scale`

**Comment by kandashi** [comment]
Ahh, I was waiting to fix an issue with the light picker that never got resolved...
