### ISSUE TITLE
Light angle is returning errors when attempting to apply with active effects

### ISSUE THREAD

**Issue by LuxuriaU** [kandashi/Active-Token-Lighting#32]
When trying to apply a light emission angle via this module on DAE (without Midi as I know it is currently broken as per the READ ME) it returns an error, informing me that light emission angle must be between 1 and 360 degrees.
The attempted value is 60, but I also tried 180 and 360. The same errors were returned.

This likely will not help, but the console's error, it seemed rather generic but here it is just in case:
`Uncaught (in promise) Error: Light emission angle must be between 1 and 360 degrees.
    at Token._validateField (opt/foundryvtt/dist/database/odm/abstract.js:1)
    at Token.validate (opt/foundryvtt/dist/database/odm/abstract.js:1)
    at Function._onUpdate (opt/foundryvtt/dist/database/odm/embedded.js:1)
    at async Socket.handleEvent (opt/foundryvtt/dist/sockets.js:1)`

**Comment by kandashi** [comment]
Can you show the details of the effect you were trying to apply

**Comment by LuxuriaU** [comment]
> Can you show the details of the effect you were trying to apply

![Screenshot (607)](https://user-images.githubusercontent.com/69419301/111071887-9857d100-84ae-11eb-908d-d63ab102d0c3.png)
Yeah, sorry, here you go. I have tried various things, making fresh items, doing it on different items, but nonetheless, the error appears.

**Comment by kandashi** [comment]
I cant seem to replicate this, is there a chance I can join your server to check

**Comment by Tupsi** [comment]
this does not work neither. But if I put the light angle into a new (own) preset it works just fine
![bullseye_preset](https://user-images.githubusercontent.com/3730499/111880908-429f8f00-89ae-11eb-903e-15241304975f.jpg)

**Comment by kandashi** [comment]
Can you send me the actor/item you are using for these tests
also just a point, you need to use UK/US `.` instead of `,` for seperating decimals

**Comment by Tupsi** [comment]
> Can you send me the actor/item you are using for these tests
[fvtt-Actor-Whitford_Lowmane (4).zip](https://github.com/kandashi/Active-Token-Lighting/files/6177029/fvtt-Actor-Whitford_Lowmane.4.zip)
> also just a point, you need to use UK/US `.` instead of `,` for seperating decimals
no, that seems to be a localisation thing. Even if I enter 0.4 and hit save, it shows up as 0,4 the next time I open it up. (Windows here is set to German locals). So both seems to work here.

**Comment by kandashi** [comment]
> no, that seems to be a localisation thing. Even if I enter 0.4 and hit save, it shows up as 0,4 the next time I open it up. (Windows here is set to German locals). So both seems to work here.
Oh interesting

**Comment by kandashi** [comment]
You should be using `override` not `add` for lightAngle properties.

I cannot replicate this on 0.2.08 with only ATL enabled
