### ISSUE TITLE
Changing token size isn't working when combined with other effects.

### ISSUE THREAD

**Issue by rockwallguy** [kandashi/Active-Token-Lighting#34]
![Screenshot (46)](https://user-images.githubusercontent.com/79724010/111708109-3df2a380-8813-11eb-82eb-6760bbd9a3d2.png)

Having an issue where the token size isn't being changed when combined with other effects.  If I delete the 4 lower effects and just leave the ATL.X effects, the token enlarges as intended.  But with the other effects included, the enlarge doesn't work.  I included a sampling of some of the errors I got while testing it.  The bottom error is the one I get when I try to use the item in the screenshot.  

If I create a second item with the 4 effects I delete to get the enlarge effect to work, it'll apply both the effects fine (though from two sources).

**Comment by kandashi** [comment]
is this applied through a Midi qol workflow?

**Comment by rockwallguy** [comment]
I think so?  I'm not exactly sure how all that works, but it's an effect on
a consumable that takes effect when the consumable is clicked on.

**Comment by rockwallguy** [comment]
[fvtt-Item-Wild_Rations_Enlarge.zip](https://github.com/kandashi/Active-Token-Lighting/files/6174483/fvtt-Item-Wild_Rations_Enlarge.zip)

This is the consumable that doesn't work.  My current workaround is having one consumable with just the lighting effects and one with just the mechanical effects.  That seems to work.

**Comment by kandashi** [comment]
Right, I found the root cause and it should be a quick fix
