### ISSUE TITLE
BUG: Animation Speed/Intensity won't drop down to minimum values

### ISSUE THREAD

**Issue by GambetTV** [kandashi/Active-Token-Lighting#44]
Animation Speed/Intensity seems to default to minimal values, but from what I can tell they move like they're set to 5. Putting them at around 6 or higher seems to make the light act extremely weird, where the light strobes into a more basic white color. My guess is when set to 1 (minimum) it's setting itself to 5, and 5 becomes 10, and above 5 sets it above 10, which I don't think Foundry knows what to do with, and causes it to flip out. Almost all my torches are set below 5 though, so this could definitely use a fix!

Thanks!

**Comment by kandashi** [comment]
Im not sure exactly what you mean here. Screenshots of the preset or Active Effect keys/values would help me troubleshoot this

**Comment by GambetTV** [comment]
Screenshots won't really help illuminate the issue. When I go into the Preset, set the Animation Type to say, Torch, and move the sliders for "Animation Speed" and "Animation Intensity" to the absolute minimum values, they act as if they're set in the middle. When I slide them to the middle, they act as if they're jacked to the max. When I set them to the max, they completely wig out.

**Comment by kandashi** [comment]
Cannot replicate nor confirm this. Closing
