### ISSUE TITLE
Removing ATL effect does not revert lighting animation

### ISSUE THREAD

**Issue by Lazytron** [kandashi/Active-Token-Lighting#45]
Hey this looks like a separate issue from the other two, so putting it in.  It seems that when an effect with ATL includes an animation, the animation value does not revert when the effect is removed (we have everyone with dim 2 so tokens and immediate surrounds are visible, so the animation is noticeable on reverting).

**Comment by kandashi** [comment]
This seems to be a bug somewhere, as testing with a new token this works as intended, however testing with a pre-existing token that has lighting pre-configured I can replicate this.
use the macro 
`token.actor.unsetFlag("ATL",  "originals")`
and change the original actors prototype token to reset this
