### ISSUE TITLE
BUG: Incompatibility with Variant Encumbrance Mod

### ISSUE THREAD

**Issue by GambetTV** [kandashi/Active-Token-Lighting#48]
Not sure why, but if you activate a Light from this mod in the Effects tab of a token, then deactivate it, and manually go into the Token Configuration under Vision and set up a new light, then do ANYTHING in your character sheet other than roll dice, such as equipping an item, favoriting an item, manually increasing the number of items of a certain type you have, reducing an item in your Feature, etc. AND you have the Variant Encumbrance mod also installed, your lights will immediately vanish, and reset to default levels.

**Comment by kandashi** [comment]
The 0.8 version of this should harden a lot of those checks. There wont be any more updates in the 0.7.9 branch
