### ISSUE TITLE
ATL.colorIntensity doesn't appear to work for effects

### ISSUE THREAD

**Issue by magroader** [kandashi/Active-Token-Lighting#54]
I was messing with adding an effect that included `ATL.colorIntensity` set to 0.5, but after setting it it was clear that the intensity was set to 1.0. Manually changing the colorIntensity on the token worked, and the effect did not seem to alter the intensity at all.

My settings were:
Attribute ATL.colorIntensity
Change Mode Override (or Custom, not sure what the difference is)
Value 0.5
Priority 20

I was using Foundry 0.8.6 and ATL 0.2.14.

**Comment by DFreds** [comment]
It was changed to lightAlpha

**Comment by kandashi** [comment]
Thanks @DFreds for pointing this out, this is now changed in the documentation
