### ISSUE TITLE
intensity and animation settings don't seem to transfer

### ISSUE THREAD

**Issue by modzy2** [kandashi/Active-Token-Lighting#56]
Not sure why I can't get this to work.
I have ATL 0.2.15 (although I was having trouble on 0.2.14 also, just not sure if it was the same). 
Foundry 0.8.8 dnd5e 1.3.6
Steps: (with only the ATL module active)
import starter hero Aoth
drag Hooded Lantern Bright (no preset) from compendium onto Aoth
equip the lantern
activate lantern effect on Aoth's effects tab
drag Aoth onto scene, the light being emitted appears just dim grey?
Open token settings, as shown, light color has updated, but -
intensity is at 0, animation settings are none/5/5
![Screenshot (23)](https://user-images.githubusercontent.com/80451044/123889531-0ad6b900-d999-11eb-8007-93d9843adf78.png)

**Comment by kandashi** [comment]
Right, the old items were not updated, silly me
