### ISSUE TITLE
Tip: Applying active effects

### ISSUE THREAD

**Issue by TPNils** [kandashi/Active-Token-Lighting#61]
Hi,

I was looking through the readme and noticed something. Regarding the active effects for light animation, active effects (regardless of midi) are not designed to work with objects. When you look into the implementation of foundry, objects always become 'flat', meaning that

```json
{
  "ATL": {
    "lightAnimation": {
      "type": "torch",
      "speed": 1,
      "intensity": 1
    }
  }
}
```
translates to
```json
{
  "ATL.lightAnimation.type": "torch",
  "ATL.lightAnimation.speed": 1,
  "ATL.lightAnimation.intensity": 1
}
```

Basically, you should never input json into effects, always primitives (and I believe arrays are pretty much impossible).
That means that the light spell can be configured as follows.

![Light spell](https://user-images.githubusercontent.com/6439997/124368936-9769cb80-dc66-11eb-9b56-ef3379c46b88.png)

As an additional note, it is a best practice to use `flags.<module-name>` as a prefix. The `ATL` works for effects since the data is not stored directly onto the item, but if you would want to store the data onto the item itself, it would get removed since foundry enforces a strict data structure. Changing this now would obviously be a breaking change so changing it now would be a bad idea. Just thought I would let you know for future reference.

**Comment by kandashi** [comment]
ATL no longer uses a flag system, but has its own type reading for active effects. So this should not be an issue going forwards. 
Im not *exactly* sure what you are refering to with the json objects...

**Comment by TPNils** [comment]
Maybe this example is clearer, this is how the torch without preset should be configured to be able to work. Don't use JSON in the Effect Value input
![image](https://user-images.githubusercontent.com/6439997/125208182-3dce5600-e291-11eb-9125-0d5bcf108f64.png)

**Comment by kandashi** [comment]
Im pretty sure the json format will work, it has a *little* bug currently about number/string formatting

**Comment by kandashi** [comment]
It is stored as a string, then parsed into a json when applied later

**Comment by TPNils** [comment]
I guess that would work. The method I listed does not need manual conversion, in case you are interested.
I thought I would mention it since the readme states there is/was an issue

### Complications

- At the moment ATL.lightEffect will not correctly apply if this effect is applied through Midi QoL

**Comment by kandashi** [comment]
Both are possible, though I went with the json method to keep individual effects to a minimum. However complicated lighting should be handled by presets by preference
