### ISSUE TITLE
Lighting not applied correctly

### ISSUE THREAD

**Issue by federicofrontera** [kandashi/Active-Token-Lighting#63]
When first adding a lighting item to a token it works. The effect can be toggled by equipping/unequiping the item. I'm not sure what the trigger is but at some point it stops working and lighting is no longer applied. 
It seems to be a on a token by token basis (works for some PCs but not others).

This is the vision data before applying any effect
![vision before torch](https://user-images.githubusercontent.com/19600156/124925438-d1263380-dfd2-11eb-9a3e-38de6d2228cc.png)

And this is after equipping torch:
![vision after effect](https://user-images.githubusercontent.com/19600156/124925633-06cb1c80-dfd3-11eb-9691-62ba488254e0.png)

Finally this is the effect on the sheet:
![torch equipped and effect](https://user-images.githubusercontent.com/19600156/124925838-3e39c900-dfd3-11eb-80ea-874899049ba6.png)

On further inspection I noticed the lighting is applied to the prototype token instead of the "active token"  when activating/deactivating the lighting effect.

**Comment by ravingdragoon** [comment]
> On further inspection I noticed the lighting is applied to the prototype token instead of the "active token" when activating/deactivating the lighting effect.
So, the issue that is causing this is that the module is not targeting the uuid of the token, and is just targeting the prototype instead?
