### ISSUE TITLE
Bug: Error when using Goggles of Night for dimSight

### ISSUE THREAD

**Issue by caewok** [kandashi/Active-Token-Lighting#64]
**Describe the bug**
When equipping or un-equipping Goggles of Night, I get an error: `Invalid PrototypeTokenData dimSight distance which must be a number with absolute value less than 1000`. The effect appears to be enabled but no changes are made to the dimVision for the token. I.e., no +60 feet of dimVision.

**To Reproduce**
1. Add Goggles of Night from the ATL pre-defined item compendium to the token.
2. Equip the Goggles.
3. See error

**Expected behavior**
I would expect the effect to change the dimVision from 0 (for this particularly token) to 60. 

**Details**

> Error: [wy6njyR3ONNXktrD] Invalid TokenData dimSight distance which must be a number with absolute value less than 1000
>     _validateField https://vtt.planeteternium.com/common/abstract/data.mjs:382
>     validate https://vtt.planeteternium.com/common/abstract/data.mjs:273
>     _preUpdateDocumentArray https://vtt.planeteternium.com/scripts/foundry.js:8766
>     _updateEmbeddedDocuments https://vtt.planeteternium.com/scripts/foundry.js:8728
>     update https://vtt.planeteternium.com/common/abstract/backend.mjs:153
>     updateDocuments https://vtt.planeteternium.com/common/abstract/document.mjs:366
>     update https://vtt.planeteternium.com/common/abstract/document.mjs:448
>     applyEffects https://vtt.planeteternium.com/modules/ATL/src/activeLighting.js:517
>     ready https://vtt.planeteternium.com/modules/ATL/src/activeLighting.js:86
>     _call https://vtt.planeteternium.com/scripts/foundry.js:194
>     callAll https://vtt.planeteternium.com/scripts/foundry.js:153
>     callback https://vtt.planeteternium.com/scripts/foundry.js:8880
>     documents https://vtt.planeteternium.com/scripts/foundry.js:8850
>     _handleUpdateEmbeddedDocuments https://vtt.planeteternium.com/scripts/foundry.js:8850
>     _updateEmbeddedDocuments https://vtt.planeteternium.com/scripts/foundry.js:8739
>     update https://vtt.planeteternium.com/common/abstract/backend.mjs:153
>     updateDocuments https://vtt.planeteternium.com/common/abstract/document.mjs:366
>     updateEmbeddedDocuments https://vtt.planeteternium.com/common/abstract/document.mjs:532
>     preUpdateItem https://vtt.planeteternium.com/modules/dae/module/dae.js:1292
>     _call https://vtt.planeteternium.com/scripts/foundry.js:194
>     callAll https://vtt.planeteternium.com/scripts/foundry.js:153
>     callback https://vtt.planeteternium.com/scripts/foundry.js:8880
>     documents https://vtt.planeteternium.com/scripts/foundry.js:8850
>     _handleUpdateEmbeddedDocuments https://vtt.planeteternium.com/scripts/foundry.js:8850
>     _updateEmbeddedDocuments https://vtt.planeteternium.com/scripts/foundry.js:8739
>     update https://vtt.planeteternium.com/common/abstract/backend.mjs:153
>     updateDocuments https://vtt.planeteternium.com/common/abstract/document.mjs:366
>     update https://vtt.planeteternium.com/common/abstract/document.mjs:448
>     _updateObject https://vtt.planeteternium.com/scripts/foundry.js:3252
>     _onSubmit https://vtt.planeteternium.com/scripts/foundry.js:2818
>     _onSubmit https://vtt.planeteternium.com/systems/dnd5e/module/item/sheet.js:347
>     _onChangeInput https://vtt.planeteternium.com/scripts/foundry.js:2866
>     jQuery 8
>     activateListeners https://vtt.planeteternium.com/scripts/foundry.js:2765
> foundry.js:8769:17
> Invalid PrototypeTokenData dimSight distance which must be a number with absolute value less than 1000

**Environment:**
 - OS: MacOS 10.15.17
 - Browser Firefox 90.0
 - Foundry Version 0.8.8
 - Module Version [e.g 0.1.42]
 - All Modules Disabled: Yes except:
 - Module List if no: ATL 0.2.16, DAE 0.8.31
- dnd5e 1.3.6

**Additional context**
I also cannot make ATL.dimSight work as a dynamic active effect otherwise. (Like, if I create my own specialized effect.) So I don't think it is the Goggles, per se, but rather something with how the +60 is being added to dimVision. I suspect Foundry's more recent additional checks to data fields is catching something---maybe a string where it expects a number?

**Comment by kandashi** [comment]
Can you confirm which version of ATL you are on, as I cannot replicate this on the latest release

**Comment by caewok** [comment]
I am using ATL 0.2.16.
