### ISSUE TITLE
Error when using presets

### ISSUE THREAD

**Issue by MSAbaddon** [kandashi/Active-Token-Lighting#65]
When I use ATL-preset I get an error message as soon as the effect is applied:

![image](https://user-images.githubusercontent.com/66370966/129314568-35357ab3-79d1-4274-84d5-9edd9f38ef97.png)

**Comment by kandashi** [comment]
Go into the preset menu, open `torch` and then save. That should fix it

**Comment by MSAbaddon** [comment]
Thanks for the reply - updating the presets solved the issue :-)
