### ISSUE TITLE
Effects don't toggle if the GM is in a different Scene (5e)

### ISSUE THREAD

**Issue by Baronvonburp** [kandashi/Active-Token-Lighting#67]
**Describe the bug**
Applying or removing the ATL.dimVision (or bright) while the GM is not on the same scene as the token will not apply or remove the vision modifier to the token. Potentially applies to other effects, but I have not tested it.

**To Reproduce**
1. Open a session
2. Login as the GM, and login as a player on a seperate browser
3. Move the GM to a different screen than the players
4. toggle the effect on either browser
5. Watch the effect not get toggled
6. _Grofit._

**Expected behavior**
I expected the effect to be toggled.

**Environment:**
 - OS: Win10
 - Browser Foundry's browser, Chrome, Firefox
 - Foundry Version e.g. 0.8.8 & 0.8.9
 - Module Version e.g 0.2.17
 - All Modules Disabled: Yes
 - Module List if no:  Only Active token lighting.

**Comment by kandashi** [comment]
This is an unfortunate byproduct that dosnt have an easy answer im afriad
