### ISSUE TITLE
Removing effect doesn't return light back to 0

### ISSUE THREAD

**Issue by kaelad02** [kandashi/Active-Token-Lighting#69]
**Describe the bug**
Changing the prototype token's light settings aren't used when turning off an effect that gives off light (e.g. a torch).

**To Reproduce**
1. The actor's prototype token had dimLight of 40 and brightLight of 20
2. I used DFreds Convenient Effects to add a torch and it worked. Had the right distances, color, and animation.
3. Then I removed the effect and the tokens vision returned to the previous 40/20 with no color or animation.
4. I removed the light from the prototype token. Now the prototype doesn't have a built-in light source.
5. I removed the token and re-added it to the scene to use the prototype token settings.
5. I added the torch back with DCE and it worked
6. I removed the torch effect and the light on the token returned to that original 40/20.

**Expected behavior**
The light should have returned to what it was before the effect was added/enabled

**Environment:**
 - OS: Windows 10
 - Browser: built-in Electron
 - Foundry Version: 0.8.9
 - Module Version: 0.2.17
 - All Modules Disabled: No
 - Module List if no: DFreds Convenient Effects, Dice So Nice, Group Initiative, libWrapper, Select tool everywhere, socketlib, Token Action HUD, Token Attacher

**Additional context**
I opened the console to take a look at the actor data. I notice that there's something in `data.flags.ATL` that might be relevant:
```json
{
  "originals": {
    "dimLight": 40,
    "brightLight": 20,
    "lightColor": null,
    "lightAlpha": 1,
    "lightAnimation": {
      "speed": 5,
      "intensity": 5
    }
  }
}
```
It seems like ATL captured the original settings from the first time I added an effect. But I changed the token's settings, even the prototype but it looks like it keeps using the `originals` setting it captured the first time.

**Comment by kandashi** [comment]
If you remove any ATL effects on the actor, then run the macro `actor.unsetFlag("ATL", "originals")` this will wipe that old data and re-set the system
