### ISSUE TITLE
error "updateManager" in the console on stratup

### ISSUE THREAD

**Issue by CaosFR** [kandashi/Active-Token-Lighting#72]
Hi,

Since last update I have a bug. Thanks for your help and work.

**Describe the bug**
I have a error in the console on stratup.

**To Reproduce**
1. Go to 'A DnD 5e party'
2. Click on 'F12'
3. Scroll down to 'Uncaught (in promise) ReferenceError'

**Expected behavior**
Solve the error

**Screenshots**
Uncaught (in promise) ReferenceError: updates is not defined
[Detected 1 package: ATL]
at Function.v9UpdateActor (updateManager.js:66)
at async Function.v9Update (updateManager.js:161)
  | v9UpdateActor | @ | updateManager.js:66
  | await in v9UpdateActor (async) |   |  
  | runUpdates | @ | updateManager.js:10
  | _call | @ | VM5157:4
  | callAll | @ | foundry.js:153
  | setupGame | @ | foundry.js:4403
  | await in setupGame (async) |   |  
  | _initializeGameView | @ | foundry.js:5213
  | _initializeView | @ | foundry.js:5189
  | initialize | @ | foundry.js:4286
  | await in initialize (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:502
  | 🎁libWrapperInit | @ | libWrapper-api.js:778
  | await in 🎁libWrapperInit (async) |   |  
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:182
  | window.addEventListener.once | @ | foundry.js:53613

**Environment:**
 - OS: Windows
 - Browser Chromium
 - Foundry Version 0.8.9
 - Module Version 0.3.0
 - All Modules Disabled: Yes

Thanks for your help.

**Comment by CaosFR** [comment]
Hi, it's solve ?

**Comment by kandashi** [comment]
should be yes
