### ISSUE TITLE
Luminosity number field doesn't reflect change in scale value in ATL preset editor

### ISSUE THREAD

**Issue by ctbritt** [kandashi/Active-Token-Lighting#74]
**Describe the bug**

**To Reproduce**
1. Click on the lights layer
2. Click the ATL Presets Button
3. Select Light
4. Choose Update
5. Try to change Luminosity value with slider
6. Value in the text field to the right of slider never changes. Stays at 0.5

**Expected behavior**
Value shown should track the slider scale's value.

**Screenshots**
<img width="397" alt="Screen Shot 2021-12-21 at 2 43 36 PM" src="https://user-images.githubusercontent.com/4516034/146988685-2536e331-9e1d-4ab6-9450-1acd412fc02e.png">
<img width="404" alt="Screen Shot 2021-12-21 at 2 43 43 PM" src="https://user-images.githubusercontent.com/4516034/146988696-faa3ed88-fbf0-4921-a54f-056d5308c63d.png">

**Environment:**
 - OS: macOS
 - Browser Chrome
 - Foundry Version 9.238
 - Module Version 0.3.01
 - All Modules Disabled: No
 - Module List if no: ATL, ItemMacro, DAE, midi-qol, advanced macros, lib-wrapper, socketlib

**Additional context**

**Comment by kandashi** [comment]
Ah yeah... im not actually sure if I can do anything about this as its a Dialog not a Form
