### ISSUE TITLE
preset error & no size option in active effects

### ISSUE THREAD

**Issue by SR5060** [kandashi/Active-Token-Lighting#75]
Foundry 0.8.9
Dnd 5e 1.5.5
ATL 0.3.01

size parameter does not appear in active effect ATL.X options, ATL.GeneratePreset() errors out
![image](https://user-images.githubusercontent.com/85184490/147113907-14e95458-999c-4862-ac4b-71d360138fca.png)
 
not sure if this is due to 0.8.x incompatibility or something else

**Comment by grendel111111** [comment]
I'm getting this error when I go to modify or make a preset:
![image](https://user-images.githubusercontent.com/80164119/147162999-5da3fd91-480f-426d-8983-91df8c4264ae.png)
Foundry 0.8.9
Using Savage worlds (SWADE)

**Comment by kandashi** [comment]
ATE v3 + is for foundry V9 and above only, please manually install 0.2.17

**Comment by SR5060** [comment]
This still seems to be an issue with v9

ATL 0.3.05
Foundry 9.238
dnd5e 1.5.6
