### ISSUE TITLE
Doesn't seem to work in V9

### ISSUE THREAD

**Issue by SLinxTheFox** [kandashi/Active-Token-Lighting#77]
Using lighting effects has no effect at all after updating to V9

Screenshot of effects and the token not being lit up
https://i.imgur.com/uAcRt9B.png

done in the foundry program on windows 10 V9

Module List:

ATL
betterrolls5e
cleaner-sheet-title-bar
combat-carousel
combat-numbers
combat-utility-belt
compendium-folders
cursor-hider
custom-css
dae
ddb-importer
dfreds-convenient-effects
easy-ruler-scale
forien-copy-environment
fuzzy-foundry
hide-gm-rolls
koboldworks-ready-up
lib-wrapper
mcromusic-sampler
monsterblock
perfect-vision
settings-extender
smalltime
splatter
tagger
token-animation-tools
token-info-icons
unsnap-ruler
window-controls
zoom-pan-options
_CodeMirror
_mathjs
resourcesplus
adventuremusic
animation-preview
betternpcsheet5e
betterroofs
beyond20
boy-king-of-idaho-music-pack
character-actions-list-5e
chat-images
compact-beyond-5e-sheet
compendium-browser
custom-pause
5e-ogl-character-sheet
drag-ruler
forien-token-rotation
forien-unidentified-items
graham-plowmans-music-pack
healthEstimate
illandril-inventory-sorter
ivan-duch-music-packs
JB2A_DnD5e
colorsettings
lib-df-hotkeys
link-item-resource-5e
long-rest-hd-healing
lootsheetnpc5e
monks-tokenbar
multilevel-tokens
music-d20-sampler
playlist-down
popout
resource-icons
SharedCompendiums
socketlib
tabletop-music-bazaar-free
tabletop-rpg-music
ThandulsTogglableEffects
tidy-ui_game-settings
token-health
variant-encumbrance-dnd5e
wall-height

**Comment by kandashi** [comment]
Those are the wrong attribute keys, you can run the command `ATLUpdate.v9UpdateActor(actor)` to update to the new keys after updating to the latest version
