### ISSUE TITLE
Active Effects on characters are deleted when Foundry loads

### ISSUE THREAD

**Issue by amcvfx** [kandashi/Active-Token-Lighting#78]
**Describe the bug**
With Active Token Effects activated, whenever Foundry loads, all Active Effects (the actual effects, not the entry in the Effects page) are deleted. With the Module off, the active effects remain intact.
I haven't upgraded to v9 yet as not all of my modules are ready.

**To Reproduce**
Running only:
MidiQOL
Dynamic Active Effects
socketlib
libWrapper
Active Token Effects
I used Find the Culprit to discover the issue.

**Environment:**
 - Chrome
 - Foundry Version 0.8.9
 - Module Version 0.3.04

**Comment by kandashi** [comment]
return to 0.2.17, this version was not meant for <v9
