### ISSUE TITLE
Preset error & no size option

### ISSUE THREAD

**Issue by SR5060** [kandashi/Active-Token-Lighting#79]
This still seems to be an issue with v9

ATL 0.3.05
Foundry 9.238
dnd5e 1.5.6

_Originally posted by @SR5060 in https://github.com/kandashi/Active-Token-Lighting/issues/75#issuecomment-1003138872_

**Comment by kandashi** [comment]
Please be a litte more specific with what the exact issue is alongside modlist, console errors etc

**Comment by SR5060** [comment]
The preset function seems to be broken (Or I'm missing something in your instructions). I've tried using both the console and a macro and they trigger the same error message:

![image](https://user-images.githubusercontent.com/85184490/147864452-179872ec-d5c7-4fe7-b10e-a104ff1cae0f.png)

**Comment by SR5060** [comment]
I've tried running this without any other modules and it does not appear to impact the issue

**Comment by crymic** [comment]
Could be also a root issue
`activeLighting.js:645 Uncaught (in promise) TypeError: ATL.applyCustom is not a function`

**Comment by kandashi** [comment]
> The preset function seems to be broken (Or I'm missing something in your instructions). I've tried using both the console and a macro and they trigger the same error message:
> 
> ![image](https://user-images.githubusercontent.com/85184490/147864452-179872ec-d5c7-4fe7-b10e-a104ff1cae0f.png)
> 
> 

What "preset function" are you on about?

**Comment by SR5060** [comment]
ATL.GeneratePreset()
