### ISSUE TITLE
Lighting Effect "weird default" + Strange Issue

### ISSUE THREAD

**Issue by JeffreyRijkse** [kandashi/Active-Token-Lighting#80]
Hey there, just ran into two strange issues which I think are related.

Any time I assign a lighting effect to a token the lighting config seems to change back to a strange default as well as alter the lighting angle to 60*

Steps to reproduce:

1. Set tokens default lighting
![1](https://user-images.githubusercontent.com/78631300/148329330-536e3f47-e148-4749-99cd-145e4dde737b.JPG)
2. Apply an ATL lighting effect (notice how the token defaulted to this 60 degree angle view even though the effect did not specify
![2](https://user-images.githubusercontent.com/78631300/148329332-b95ade5a-9d16-4258-86ed-6312ee28d5e2.JPG)
![3](https://user-images.githubusercontent.com/78631300/148329333-bf16d2ec-7f66-4157-b40d-d9c2d60684eb.JPG)
3. Remove the effect - notice it is not the same as the "default" lighting set in step 1
![4](https://user-images.githubusercontent.com/78631300/148329334-36e9a396-6b6f-4239-ad6a-778688e1c91f.JPG)

I tried changing the default prototype token multiple times and while it saves, as soon as I apply the new lighting and remove it it reverts back for some reason (different per token/actor).

**Comment by JeffreyRijkse** [comment]
On a different character notice how the default for step 3 is something different

![Default #2](https://user-images.githubusercontent.com/78631300/148329632-ecc8e0c8-b281-4252-bf57-4c148737d214.JPG)

**Comment by kandashi** [comment]
This is due to a few errors in the baseline theory for the module, should not be present in https://github.com/kandashi/Active-Token-Lighting/tree/new-proto-rework
