### ISSUE TITLE
Error message on 0.8.9: `updateManager.js:66 Uncaught (in promise) ReferenceError: updates is not defined`

### ISSUE THREAD

**Issue by jocolamarco** [kandashi/Active-Token-Lighting#81]
**Describe the bug**
Error message on v8:
`updateManager.js:66 Uncaught (in promise) ReferenceError: updates is not defined`

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a world with ATL active
2. Open the console log
3. See error

**Expected behaviour**
Error message displayed after recent updates (but still on V8)

**Screenshots**
![imagem](https://user-images.githubusercontent.com/45291719/148537710-666d4c06-7c85-4f67-bfe3-697faf4e74c3.png)

![imagem](https://user-images.githubusercontent.com/45291719/148537897-14207249-6610-4ca8-858c-cc02490c589d.png)

![imagem](https://user-images.githubusercontent.com/45291719/148538207-73471a2b-f5a5-41cd-94fc-67ff22654c64.png)

**Environment:**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] chrome
 - Foundry Version [e.g. 0.8.8] 0.8.9
 - Module Version [e.g 0.1.42] 0.3.0
 - All Modules Disabled: No
 - Module List if no: n/a

**Additional context**
no further updates for v8

**Comment by kandashi** [comment]
Dont use 0.3+ on v8, downgrade to 0.2.17

**Comment by jocolamarco** [comment]
OK, I'll check it. I think this was automatically updated without checking the version number?
