### ISSUE TITLE
[BUG] Multiple ATL effects on the same character

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Active-Token-Lighting#83]
**Describe the bug**
Let's assume a `linked` character with two ATL effects:
- One passive without duration
- One active with a duration (like a torch)

Upon adding the second effect, everything if OK.
But when deleting the second active effect from the canvas token, the prototype token data is not reverted to the previous (no active effect) configuration.

**To Reproduce**
1. Create a **linked** character
2. Create a **passive** effect, something like: ATL.dimSight ➡️ 18 OVR
3. Now place the token on the canvas
4. Open the character sheet and create a new active effect like: ATL.light.bright ➡️ 24 OVR (duration 1 hour)
5. Observe that both active effects are working correctly on the canvas
6. Remove the second active effect (ATL.light.bright)
7. Observe that the second active effect has been successfully removed on the canvas
8. remove the token from the canvas
9. Add a new instance of the character token onto the canvas
10. Although the second active effect isn't on the actor anymore, the ATL configuration remains the same on the **prototype token** as when the effect was active

**Expected behavior**
Deletion of an active effect should propagate to the proptotype token, event with multiple active effects.

**Environment:**
 - OS: Windows
 - Browser:  Chrome
 - Foundry Version:  9.241
 - Module Version:  0.3.05
 - All Modules Disabled: No
 - Module List if no: The usual suspects (DAE, Perfect vision, etc.)

**Additional context**
Think that wasn't an issue with FVTT 0.8

**Comment by kandashi** [comment]
Should be fixed in https://github.com/kandashi/Active-Token-Lighting/tree/new-proto-rework
