### ISSUE TITLE
[BUG] Migration issue

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Active-Token-Lighting#84]
**Describe the bug**
With the new FVTT version, light data on characters changed.
I had this issue where I had to empty the ATL flags in order to have ATL handling the removing of an active effect correctly. It was trying to go back to 0.8 data structure.

I think this package should ensure that old ATL flags are gone.

**To Reproduce**
1. Create a character with a light with FVTT 0.8.9
2. Migration to v9
3. Check the character ATL flags

**Environment:**
- OS: Windows
- Browser: Chrome
- Foundry Version: 9.241
- Module Version: 0.3.05
- All Modules Disabled: No
- Module List if no: The usual suspects (DAE, Perfect vision, etc.)

**Comment by kandashi** [comment]
There is a migration stucture in place for ATL flags, but it is not 100% perfect. You might need to manually adjust some effects if they are not fully migrated
