### ISSUE TITLE
Allow ATE to update boolean values of token data

### ISSUE THREAD

**Issue by paulohdsc** [kandashi/Active-Token-Lighting#88]
I've tried to use Active Token Effects to toggle the Gradual Illumination of a token using `ATL.light.gradual > Override > false` and `ATL.light.gradual > Add > false`, with no success.

Asking about it at Foundry Discord, you answered that "ATE never had to deal with boolean stuff before, so I doubt it will work", and recommended me to open an issue for you to take a look, so here I am.

**Comment by kandashi** [comment]
Fixed in https://github.com/kandashi/Active-Token-Lighting/tree/new-proto-rework
