### ISSUE TITLE
Allow for image overrides to be made with flags

### ISSUE THREAD

**Issue by paulohdsc** [kandashi/Active-Token-Lighting#89]
It would be nice to allow for image overrides to be made with flags, in the same way it is possible for the size. This way, when enabling an effect with `ATL.img`, the current image of the token is saved in a flag, so that after disabling the effect the token returns to the previous image. It would be especially useful for tokens making use of wildcard images.

**Comment by kandashi** [comment]
That's the way it should function...

**Comment by paulohdsc** [comment]
I tested it again. With no wildcard it works normally. But with Randomize Wildcard Images enabled, I get this error message:

![chrome_GPGSz0nKCh](https://user-images.githubusercontent.com/75817094/152658961-3511f6b5-8405-405a-92c2-240c24445d69.jpg)

**Comment by kandashi** [comment]
Wildcard image changes with ATL from now on will *not* work, but will not throw errors for normal changes on wildcard tokens
