### ISSUE TITLE
Lighting effect is happening while effect is in the "unavailable" tab.

### ISSUE THREAD

**Issue by rockwallguy** [kandashi/Active-Token-Lighting#90]
**Describe the bug**
I have a sword that is supposed to emit dim light when equipped.  I have a candle preset equipped in the sword effects.  I've also tried not using a preset and manually adding ATL.dim and other settings to replicate it, and I have the same issue.  
![image](https://user-images.githubusercontent.com/79724010/152426761-52b9dbeb-b44b-439d-9136-8b34be6c186a.png)

**To Reproduce**

When I move the sword to the token's inventory, the lighting effect happens before I equip it.  You can see that the effect ("Twilight") is in the unavailable section.  
![image](https://user-images.githubusercontent.com/79724010/152426866-251ed1b9-0044-4ca5-9469-d265f97c7ae5.png)

The celestial language is correctly applying only when the sword is equipped.  But I cannot get the lighting effect to turn off while the sword is in his inventory.  Removing the sword does remove the effect.  

**Expected behavior**
I would expect the lighting effect to turn on when the sword is equipped and the effect is moved to "passive effects", and to turn off when the sword is unequipped and the effect is in "unavailable effects".

**Environment:**
I'm using Windows 11, self hosting in the native app, v9 build 249 for foundry.  I'm using 0.3.06 of ATL.

**Comment by PaulWRoberts** [comment]
I am experiencing this as well.

**Comment by kaelad02** [comment]
A hint on how to fix this: I can see the module checking for active effects that are not disabled. Active effects from items that transfer to the actor on equip will be suppressed when the item isn't equipped or not attuned. So, to fix should just require changing code like this:

```js
filter(i => !i.data.disabled)
```

to this:

```js
filter(i => !i.isSuppressed && !i.data.disabled)
```

**Comment by kandashi** [comment]
This bug was an intentional feature for a while when "suppressed" was not working as it should, can now be fixed
