### ISSUE TITLE
GM Actor not Defined and User Lacks Permission to update Actor Error when ATE enabled

### ISSUE THREAD

**Issue by benpope3** [kandashi/Active-Token-Lighting#94]
**Describe the bug**
When ATE is enabled, GM gets the following console error.

updateManager.js:117 
Uncaught (in promise) ReferenceError: actor is not defined
[Detected 1 package: ATL]
at Function.v9UpdateScene (modules/ATL/src/updateManager.js:117:50)
at Function.v9Update (modules/ATL/src/updateManager.js:171:24)_

All Connected players get the following error.  If permissions are granted to that actor, or that actor is deleted, the error returns with a new actor ID.

Uncaught (in promise) Error: User Tim lacks permission to update Actor [aAyXkeZSQxuRPOQW]
[No packages detected]
at ServerDatabaseBackend._updateDocuments (/C:/FoundryVTT/resources/app/dist/database/backend/server-backend.mjs:1:3039)
at async Semaphore._try (/C:/FoundryVTT/resources/app/common/utils/semaphore.mjs:99:17)

**To Reproduce**
Disabling ATE stops the error.  Reenabling ATL starts the error.  Occurs when ATE is the only module and with other modules enabled.

**Expected behavior**
No red error or console error for users or DM

**Screenshots**
![image](https://user-images.githubusercontent.com/8761359/159137263-dd3652eb-831c-483e-91d5-073ed541543a.png)

**Environment:**
 - OS: [Win10]
 - Browser [Edge]
 - Foundry Version [e.g. 0.8.8]
 - Module Version [3.06]
 - All other Modules Disabled: Yes
 - Module List if no: 

**Additional context**
None

**Comment by kandashi** [comment]
I have reverted the automatic migration scripts in the newest version. Any updates to effects must be done by hand as a result. This will go out in https://github.com/kandashi/Active-Token-Lighting/tree/new-proto-rework
