### ISSUE TITLE
[BUG] Effect created from owned item won't work

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Active-Token-Lighting#99]
**Describe the bug**
If the effect with ATL changes is created from an owned item (like a torch), the ATL changes won't apply to the actor.

**To Reproduce**
1. Create a torch item with some ATL effects
2. Add this torch to an actor
3. Somehow, use the torch and add the active effect to the same actor (he uses his own torch)
4. The ATL changes won't be applied to the token
5. Apply the same effect with the same origin to another token (another actor), it will work

**Screenshots**
https://user-images.githubusercontent.com/1687854/163046173-6ec8eb43-dd40-429d-b74f-e996a4a3fb42.mp4

**Comment by kandashi** [comment]
Im not sure what game system thats in, but apparently it handles the active effects differently

**Comment by DarKDinDoN** [comment]
@kandashi Hello,

Sorry, forgot about the basic information.
That's actually DnD 5e with DAE under the hood.

I found the issue, it's really really weird.
Basically (DAE + MidiQol + self apply an effect on item use):
- If item === trinket. Item must be equipped for the effect to be active
- If item !== trinket (like food), Item doesn't have to be equipeed for the effect to be active

Demo video: https://user-images.githubusercontent.com/1687854/163981809-c24c36d9-53df-485d-98d6-d496d645d968.mp4

**Comment by DarKDinDoN** [comment]
Seems to be 5e system handling this way
